### ISSUE TITLE
npm test is throwing error Cache init failed during database reading

### ISSUE THREAD

**Issue by shashikumarraja** [o1lab/xmysql#10]
Please provide dev environment versions of your system

node -v **8.4.0**
( xmysql requires node >= 7.6.0 )

npm -v **5.3.0**
mysql --version **2.15.0**
xmysql --version 

- - -

Provide steps to reproduce this issue
Cloned the project
```sh
cd xmysql
npm install
npm test
```
```sh
mocha tests/*.js --exit



  xmysql : tests
Cache init failed during database reading
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
    --------------------
    at Protocol._enqueue (/Users/shashi/openSource/xmysql/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/shashi/openSource/xmysql/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/Users/shashi/openSource/xmysql/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/shashi/openSource/xmysql/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/shashi/openSource/xmysql/node_modules/mysql/lib/Pool.js:202:8)
    at Xsql.dbCacheInitAsync (/Users/shashi/openSource/xmysql/lib/xsql.js:36:15)
    at Xsql.init (/Users/shashi/openSource/xmysql/lib/xsql.js:26:10)
    at Xapi.init (/Users/shashi/openSource/xmysql/lib/xapi.js:37:16)
    at Context.<anonymous> (/Users/shashi/openSource/xmysql/tests/tests.js:42:9)
    at callFnAsync (/Users/shashi/openSource/xmysql/node_modules/mocha/lib/runnable.js:377:21)
    at Hook.Runnable.run (/Users/shashi/openSource/xmysql/node_modules/mocha/lib/runnable.js:324:7)
    at next (/Users/shashi/openSource/xmysql/node_modules/mocha/lib/runner.js:304:10)
    at Immediate._onImmediate (/Users/shashi/openSource/xmysql/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true } undefined
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                                                            
          Database              :    classicmodels
          Number of resources   :    0
                                                            
          REST APIs Generated   :    0
```

**Comment by o1lab** [comment]
Tests would need database 'classicmodels' on test system with preloaded tables and data (tests/sample.sql) 

mysql> create database classicmodels
mysql> use classicmodels
mysql> source path_to/xmysql/tests/sample.sql

Will put this up on readme
