### ISSUE TITLE
Example code throws error.

### ISSUE THREAD

**Issue by colmsjo** [o1lab/xmysql#103]
I'm using the example code and get the error below (I've updated the db credentials). Any help is much appreciated!

----
node --version
v12.16.0

npm -v
6.13.4

mysql version: 5.5.53

xmysql --version
undefined
- - -

root@nodejs:~/tmp# node index.js 
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                                                            
          Database              :    lime1
          Number of Tables      :    58
                                                            
/root/tmp/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'bold' of undefined
    at Xapi.setupRoutes (/root/tmp/node_modules/xmysql/lib/xapi.js:366:55)
    at /root/tmp/node_modules/xmysql/lib/xapi.js:37:23
    at /root/tmp/node_modules/xmysql/lib/xsql.js:24:7
    at Query.<anonymous> (/root/tmp/node_modules/xmysql/lib/xsql.js:59:13)
    at Query.<anonymous> (/root/tmp/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/root/tmp/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/root/tmp/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/root/tmp/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/root/tmp/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/tmp/node_modules/mysql/lib/protocol/Parser.js:433:10)

**Comment by ans-4175** [comment]
@colmsjo please do check my PR
