### ISSUE TITLE
SSL connection error 

### ISSUE THREAD

**Issue by Totti10as** [o1lab/xmysql#40]
@o1lab , 
 **Once i've been trying to connect via cli to the external DBserver, got the following error:
As according to the error seems that the connection been executed properly but there is additional parameter missing.
Could you please advice?**

` Generating REST APIs at the speed of your thought..

Cache init failed during database reading
Error: UNKNOWN_CODE_PLEASE_REPORT: SSL connection is required. Please specify SSL options and retry.
    at Handshake.Sequence._packetToError (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Protocol._enqueue (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\node_modules\mysql\lib\Pool.js:202:8)
    at Xsql.dbCacheInitAsync (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\lib\xsql.js:31:15)
    at Xsql.init (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\lib\xsql.js:23:10)
    at Xapi.init (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\lib\xapi.js:35:16)
    at startXmysql (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\bin\index.js:42:12)
    at start (C:\Users\Stas\AppData\Roaming\npm\node_modules\xmysql\bin\index.js:89:5) {
  code: '**UNKNOWN_CODE_PLEASE_REPORT**',
  errno: 9002,
  sqlMessage: '**SSL connection is required. Please specify SSL options and retry.\u0000**',
  sqlState: '28000',
  fatal: true
} undefined`

**Comment by shyam9813** [comment]
xmysql doesn't have an option to set the SSL mode - is this something that can be configured ?
what would be the work around for this ?
