### ISSUE TITLE
connect to remote sever timeout

### ISSUE THREAD

**Issue by luxianyou** [o1lab/xmysql#67]
mac os 11

node -v
v10.5.0

npm -v
6.4.1
mysql --version
5.7.12
xmysql --version
0.4.9

- - -

Provide steps to reproduce this issue
or
Provide minimum code to reproduce this issue
or
HTTP request,response,error snapshot of this issue

- - -
   Generating REST APIs at the speed of your thought..

Cache init failed during database reading
{ Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/Connection.js:411:13)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:444:8)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/usr/local/lib/node_modules/xmysql/node_modules/mysql/lib/Pool.js:202:8)
    at Xsql.dbCacheInitAsync (/usr/local/lib/node_modules/xmysql/lib/xsql.js:38:15)
    at Xsql.init (/usr/local/lib/node_modules/xmysql/lib/xsql.js:28:10)
    at Xapi.init (/usr/local/lib/node_modules/xmysql/lib/xapi.js:42:16)
    at startXmysql (/usr/local/lib/node_modules/xmysql/bin/index.js:44:12)
    at start (/usr/local/lib/node_modules/xmysql/bin/index.js:84:5)
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true } undefined

**Comment by o1lab** [comment]
Is the remote server on gcp/aws etc ? Atleast in case of GCP there is a need for socketPath

So try connecting successfully from just node and mysql. 

```
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret',
  database        : 'my_db'
});

pool.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
```
