### ISSUE TITLE
Error running install steps

### ISSUE THREAD

**Issue by CryptoCloudInc** [o1lab/xmysql#77]
npm install -g xmysql
xmysql -h localhost -u root -p pass -d dbname

Getting assertion I'm not understanding 
/root/.nvm/v0.10.28/lib/node_modules/xmysql/bin/index.js:19
  let app = express();
      ^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Please provide dev environment versions of your system

node -v
( xmysql requires node >= 7.6.0 )
I have v0.10.28

npm -v
1.4.9

mysql --version
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

xmysql --version

xmysql --version

Checking throws error also
/root/.nvm/v0.10.28/lib/node_modules/xmysql/bin/index.js:19
  let app = express();
      ^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

- - -

Provide steps to reproduce this issue
or
Provide minimum code to reproduce this issue
or
HTTP request,response,error snapshot of this issue

- - -

Mark issue with suitable label if it is clear what this issue is.

**Comment by o1lab** [comment]
Minimum node version required is >= 7.6.0

Your node version is v0.10.28!
