### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'c.datetime_precision' in 'field list'

### ISSUE THREAD

**Issue by mfferreira** [o1lab/xmysql#9]
Dev environment versions:
```
$ node -v
v8.5.0
$ npm -v
5.5.1
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.37, for debian-linux-gnu (x86_64) using readline 6.2
$ xmysql --version
0.0.8
```
- - -

Right after installing xmysql from npm and starting it, I get the following error.
No code changes were done.

```
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'c.datetime_precision' in 'field list'
    at Query.Sequence._packetToError (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/node_modules/mysql/lib/Pool.js:199:23)
    at Xsql.dbCacheInitAsync (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/lib/xsql.js:36:15)
    at Xsql.init (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/lib/xsql.js:26:10)
    at Xapi.init (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/lib/xapi.js:36:16)
    at Object.<anonymous> (/Users/marcoferreira/.nvm/versions/node/v8.5.0/lib/node_modules/xmysql/bin/index.js:34:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'c.datetime_precision\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql: 'select c.table_name, c.column_name, c.ordinal_position,c.column_key,c.is_nullable, c.data_type, c.column_type,c.extra,c.privileges, c.column_comment,c.column_default,c.data_type,c.character_maximum_length, c.character_octet_length,c.numeric_precision,c.numeric_scale,c.datetime_precision,c.character_set_name, c.collation_name, k.constraint_name, k.referenced_table_name, k.referenced_column_name, s.index_name,s.seq_in_index from information_schema.columns as c left join information_schema.key_column_usage as k on c.column_name=k.column_name and c.table_schema = k.referenced_table_schema and c.table_name = k.table_name left join information_schema.statistics as s on c.column_name = s.column_name and c.table_schema = s.index_schema and c.table_name = s.table_name where c.table_schema=\'gdi\' order by c.table_name, c.ordinal_position' } undefined
```

**Comment by o1lab** [comment]
@mfferreira thanks for the detailed report.

Please paste the output of following command from your mysql shell - I see a column is not found. May be its linux version of mysql 5.5.1.

```
describe information_schema.columns;
```

**Comment by o1lab** [comment]
Have pushed a change for this problem - some of the columns are available only in 5.7.x - have removed them as they are not in use. Please clone latest repo to check if it helps.

```
git clone https://github.com/o1lab/xmysql
cd xmysql
npm install
// run xmysql
```

**Comment by o1lab** [comment]
```
npm update -g xmysql
```

version 0.0.9 has the fix

**Comment by mfferreira** [comment]
Awesome. Confirmed that it's working after the update.

**Comment by mfferreira** [comment]
Sorry, just read your request for the describe now.
Here it is in case you still need it:
```
mysql> describe information_schema.columns;
+--------------------------+---------------------+------+-----+---------+-------+
| Field                    | Type                | Null | Key | Default | Extra |
+--------------------------+---------------------+------+-----+---------+-------+
| TABLE_CATALOG            | varchar(512)        | NO   |     |         |       |
| TABLE_SCHEMA             | varchar(64)         | NO   |     |         |       |
| TABLE_NAME               | varchar(64)         | NO   |     |         |       |
| COLUMN_NAME              | varchar(64)         | NO   |     |         |       |
| ORDINAL_POSITION         | bigint(21) unsigned | NO   |     | 0       |       |
| COLUMN_DEFAULT           | longtext            | YES  |     | NULL    |       |
| IS_NULLABLE              | varchar(3)          | NO   |     |         |       |
| DATA_TYPE                | varchar(64)         | NO   |     |         |       |
| CHARACTER_MAXIMUM_LENGTH | bigint(21) unsigned | YES  |     | NULL    |       |
| CHARACTER_OCTET_LENGTH   | bigint(21) unsigned | YES  |     | NULL    |       |
| NUMERIC_PRECISION        | bigint(21) unsigned | YES  |     | NULL    |       |
| NUMERIC_SCALE            | bigint(21) unsigned | YES  |     | NULL    |       |
| CHARACTER_SET_NAME       | varchar(32)         | YES  |     | NULL    |       |
| COLLATION_NAME           | varchar(32)         | YES  |     | NULL    |       |
| COLUMN_TYPE              | longtext            | NO   |     | NULL    |       |
| COLUMN_KEY               | varchar(3)          | NO   |     |         |       |
| EXTRA                    | varchar(27)         | NO   |     |         |       |
| PRIVILEGES               | varchar(80)         | NO   |     |         |       |
| COLUMN_COMMENT           | varchar(1024)       | NO   |     |         |       |
+--------------------------+---------------------+------+-----+---------+-------+
19 rows in set (0.00 sec)
```

**Comment by o1lab** [comment]
Cool. Thank you.
